packages:
    - "Projects/react-redux/**"
    - "Projects/react-rtk-query/**"
    - "Projects/react-state/**"
    - "Projects/react-useEffect/**"
    - "Projects/react-useReducer/**"
    - "Projects/react-markdoc/**"
    - "Projects/react-query/**"
    - "Projects/react-patterns/**"
